apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eve-trade

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: eve-trade
      app.kubernetes.io/managed-by: kustomize

resources:
  - base

images:
  - name: eve-trade/api-gateway
    newTag: dev
  - name: eve-trade/market
    newTag: dev
  - name: eve-trade/settlement-worker
    newTag: dev
  - name: eve-trade/trade-settlement
    newTag: dev
