apiVersion: v1
kind: ConfigMap
metadata:
  name: encore-backend-config
data:
  PORT: "4000"
  API_GATEWAY_QUILKIN_UDP_ADDR: ":26000"
  API_GATEWAY_QUILKIN_UDP_ENABLED: "true"
  TRADE_SETTLEMENT_GRPC_TARGET: "trade-settlement.eve-trade.svc.cluster.local:9092"
  OTEL_SERVICE_NAME: "encore-backend"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment.name=production,service.namespace=eve-trade"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-settlement-config
data:
  SUMMER_ENV: "prod"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment.name=production,service.namespace=eve-trade"
