apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  ENVIRONMENT: production
  API_GATEWAY_ADDR: ":8080"
  MARKET_URL: "http://market.eve-trade.svc.cluster.local:8081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-config
data:
  ENVIRONMENT: production
  MARKET_ADDR: ":8081"
  SETTLEMENT_URL: "http://trade-settlement.eve-trade.svc.cluster.local:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-settlement-config
data:
  ENVIRONMENT: production
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io/v1/traces"
  OTEL_SERVICE_NAME: "trade-settlement"
  OTEL_TRACES_EXPORTER: "otlp"
  HONEYCOMB_DATASET: "eve-trade-prod"
  RUST_LOG: "info,sqlx=info,tonic=info,h2=warn,hyper=warn,trade_settlement=debug"
  RUST_BACKTRACE: "0"
  TRACING_JSON: "true"
