apiVersion: v1
kind: Secret
metadata:
  name: honeycomb
  namespace: eve-trade-observability
  labels:
    app.kubernetes.io/name: honeycomb
    app.kubernetes.io/component: observability-secret
type: Opaque
stringData:
  api-key: "REPLACE_WITH_HONEYCOMB_INGEST_API_KEY"