apiVersion: v1
kind: Namespace
metadata:
  name: eve-trade-observability
  labels:
    name: eve-trade-observability
    app.kubernetes.io/name: eve-trade-observability
    app.kubernetes.io/component: observability
