apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eve-trade

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: eve-trade
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmaps.yaml
  - migrate.yaml
  - rabbitmq.yaml
  - api-gateway.yaml
  - market.yaml
  - settlement-worker.yaml
  - trade-settlement.yaml

configMapGenerator:
  - name: settlement-db-migrations
    files:
      - 0001_settlement_schema.sql=migrations/0001_settlement_schema.sql
      - 0002_merge_item_stack_constraints.sql=migrations/0002_merge_item_stack_constraints.sql

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: eve-trade/api-gateway
    newTag: dev
  - name: eve-trade/market
    newTag: dev
  - name: eve-trade/settlement-worker
    newTag: dev
  - name: eve-trade/trade-settlement
    newTag: dev
