apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "eve_trade"
  RABBITMQ_DEFAULT_PASS: "replace-me"
  RABBITMQ_URL: "amqp://eve_trade:replace-me@rabbitmq:5672/"
