apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: market
  labels:
    app.kubernetes.io/name: market
    app.kubernetes.io/component: market
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: settlement-worker
  labels:
    app.kubernetes.io/name: settlement-worker
    app.kubernetes.io/component: settlement-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trade-settlement
  labels:
    app.kubernetes.io/name: trade-settlement
    app.kubernetes.io/component: settlement
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
automountServiceAccountToken: false
