apiVersion: v1
kind: ServiceAccount
metadata:
  name: encore-backend
  labels:
    app.kubernetes.io/name: encore-backend
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trade-settlement
  labels:
    app.kubernetes.io/name: trade-settlement
    app.kubernetes.io/component: settlement
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsqd
  labels:
    app.kubernetes.io/name: nsqd
    app.kubernetes.io/component: pubsub
automountServiceAccountToken: false
