from __future__ import annotations

"""Sealed source-authoritative and clean-deployment verification campaign."""

from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import sys
import tempfile
import tomllib


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "infra"))
sys.path.insert(0, str(ROOT / "infra" / "law_tests"))

from agentinfra.atomic import atomic_write_json, atomic_write_bytes
from agentinfra.audit import audit
from agentinfra.final_audit import REQUIRED_FINAL_AUDIT_CHECKS, finalize_audit, seal_audit_observation
from agentinfra.governance import capture_governance
from agentinfra.manifest import verify as verify_manifest
from agentinfra.process import run_process
from agentinfra.release_source import (
    GENERATED_SOURCE_DIRECTORIES,
    SOURCE_DIRECTORIES,
    SOURCE_FILES,
    build_deployment_tree,
    validate_version_consistency,
    verify_deployment_tree,
)
from agentinfra.workspace import workspace_fingerprint
from build_traceability import FINAL_STATUSES, build as build_traceability
from constitutional_catalog import constitutional_report_is_acceptable


def canonical_digest(value: object) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, default=str, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def execute(
    label: str,
    argv: list[str],
    cwd: Path,
    *,
    expected: frozenset[int] = frozenset({0}),
    timeout: float = 900.0,
) -> tuple[dict, str]:
    result = run_process(argv, cwd=cwd, timeout=timeout, capture_limit=512_000)
    record = {
        "label": label,
        "argv": list(result.argv),
        "exit": result.returncode,
        "timed_out": result.timed_out,
        "duration_seconds": result.duration_seconds,
        "stdout_bytes": result.stdout_bytes,
        "stderr_bytes": result.stderr_bytes,
        "stdout_sha256": result.stdout_sha256,
        "stderr_sha256": result.stderr_sha256,
    }
    if result.timed_out or result.returncode not in expected:
        raise RuntimeError(
            f"{label} failed: {record}; stdout={result.stdout[-4000:]!r}; stderr={result.stderr[-4000:]!r}"
        )
    return record, result.stdout


def source_inventory(root: Path) -> list[Path]:
    files = [root / relative for relative in SOURCE_FILES if (root / relative).is_file()]
    for relative in SOURCE_DIRECTORIES:
        directory = root / relative
        if directory.is_dir():
            files.extend(
                path
                for path in directory.rglob("*")
                if path.is_file()
                and not any(
                    part in GENERATED_SOURCE_DIRECTORIES
                    for part in path.relative_to(directory).parts
                )
            )
    return sorted(set(files), key=lambda path: path.relative_to(root).as_posix())


def static_source_validation(root: Path) -> dict:
    counts: Counter[str] = Counter()
    digests: dict[str, str] = {}
    forbidden: list[str] = []
    secret_patterns = (
        re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        re.compile(r"(?i)\b(?:api[_-]?key|access[_-]?token|password)\s*=\s*['\"][^'\"]{12,}['\"]"),
    )
    secret_hits: list[str] = []
    for path in source_inventory(root):
        relative = path.relative_to(root).as_posix()
        if path.name == "__pycache__" or path.suffix in {".pyc", ".pyo"}:
            forbidden.append(relative)
            continue
        payload = path.read_bytes()
        digests[relative] = hashlib.sha256(payload).hexdigest()
        if path.suffix == ".py":
            text = payload.decode("utf-8")
            compile(text, str(path), "exec")
            counts["python"] += 1
            if "/tests/" not in "/" + relative and "/property_tests/" not in "/" + relative and "/law_tests/" not in "/" + relative:
                if any(pattern.search(text) for pattern in secret_patterns):
                    secret_hits.append(relative)
        elif path.suffix == ".toml":
            tomllib.loads(payload.decode("utf-8"))
            counts["toml"] += 1
        elif path.suffix == ".json":
            json.loads(payload)
            counts["json"] += 1
    if forbidden:
        raise RuntimeError(f"source inventory contains generated bytecode: {forbidden}")
    if secret_hits:
        raise RuntimeError(f"source production inventory contains credential-like literals: {secret_hits}")
    version = validate_version_consistency(root)
    if not version["ok"]:
        raise RuntimeError(f"source version metadata drift: {version['mismatches']}")
    return {
        "counts": dict(sorted(counts.items())),
        "file_count": len(digests),
        "inventory_sha256": canonical_digest(digests),
        "version": version,
        "secret_hits": secret_hits,
    }


def _behavioral_production_path(relative: str) -> bool:
    path = Path(relative.replace("\\", "/"))
    parts = path.parts
    if relative in {"framework.toml", "workspace-policy.toml"}:
        return True
    if len(parts) == 2 and parts[0] in {"core", "protocols", "templates"} and path.suffix in {".md", ".toml"}:
        return True
    if parts == ("bootstrap", "root-AGENTS.block.md"):
        return True
    if parts and parts[0] == "bootstrap" and path.suffix == ".py":
        return True
    if parts and parts[0] == "bin" and path.suffix in {".py", ".ps1", ".sh", ".xsh"}:
        return True
    if len(parts) >= 2 and parts[0] == "modules":
        return (
            path.suffix == ".py"
            or path.name in {"module.toml", "POLICY.md"}
            or ("roles" in parts and path.suffix == ".md")
            or ("config" in parts and path.suffix == ".toml")
        )
    if len(parts) == 2 and parts[0] == "laws" and path.suffix == ".toml":
        return True
    if len(parts) >= 3 and parts[:2] == ("infra", "agentinfra") and path.suffix == ".py":
        return True
    if len(parts) == 3 and parts[:2] == ("infra", "laws") and path.suffix == ".toml":
        return True
    if len(parts) == 3 and parts[:2] == ("infra", "law_tests"):
        return (
            path.suffix == ".py" and not path.name.startswith("test_")
        ) or path.name == "semantic_catalog.json"
    if len(parts) == 2 and parts[0] == "scripts" and path.suffix == ".py":
        return True
    return False


def _git_changed_paths(root: Path) -> list[str]:
    commands = (
        ["git", "diff", "--name-only", "--diff-filter=ACMRTUXB", "HEAD", "--"],
        ["git", "ls-files", "--others", "--exclude-standard"],
    )
    changed: set[str] = set()
    for argv in commands:
        result = run_process(argv, cwd=root, timeout=30, capture_limit=256_000)
        if result.timed_out or result.returncode != 0:
            raise RuntimeError(f"cannot derive changed source inventory for TDD provenance: {argv}: {result.stderr[-1000:]}")
        for raw in result.stdout.splitlines():
            relative = raw.strip().replace("\\", "/")
            if relative:
                changed.add(relative)
    return sorted(changed)


def _validate_production_tdd_map(root: Path, *, cycle_ids: set[str], changed_paths: list[str]) -> dict:
    production = sorted(path for path in changed_paths if _behavioral_production_path(path))
    map_path = root / ".aegis" / "audit" / "tdd-production-map.json"
    try:
        mapping = json.loads(map_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"production TDD map is missing or invalid: {exc}") from exc
    records = mapping.get("production_files") if isinstance(mapping, dict) else None
    if (
        mapping.get("schema") != 1
        or not isinstance(mapping.get("baseline_revision"), str)
        or not mapping["baseline_revision"].strip()
        or not isinstance(records, dict)
    ):
        raise RuntimeError("production TDD map failed schema validation")
    missing = sorted(set(production) - set(records))
    extra = sorted(set(records) - set(production))
    if missing or extra:
        raise RuntimeError(f"production TDD map is not an exact changed-file bijection; missing={missing}; extra={extra}")
    validated: list[dict] = []
    for relative in production:
        record = records[relative]
        path = root / relative
        if (
            not isinstance(record, dict)
            or record.get("classification") != "behavioral-production"
            or not isinstance(record.get("rationale"), str)
            or not record["rationale"].strip()
            or not isinstance(record.get("cycles"), list)
            or not record["cycles"]
            or len(record["cycles"]) != len(set(record["cycles"]))
            or any(cycle not in cycle_ids for cycle in record["cycles"])
        ):
            raise RuntimeError(f"production TDD map record is invalid or names an unknown cycle: {relative}")
        if not path.is_file():
            raise RuntimeError(f"production TDD map target is not a file: {relative}")
        current = file_sha256(path)
        if record.get("sha256") != current:
            raise RuntimeError(f"production TDD map digest is stale: {relative}")
        validated.append({"path": relative, "sha256": current, "cycles": record["cycles"]})
    return {
        "baseline_revision": mapping["baseline_revision"],
        "changed_production_files": len(validated),
        "changed_nonproduction_files": len(set(changed_paths) - set(production)),
        "records": validated,
        "digest": canonical_digest(validated),
    }


def validate_tdd_provenance(root: Path, *, changed_paths: list[str] | None = None) -> dict:
    directory = root / ".aegis" / "audit" / "tdd"
    paths = sorted(directory.glob("TDD-*.json"))
    if not paths:
        raise RuntimeError("TDD provenance directory contains no cycles")
    cycles: list[dict] = []
    aborted: list[dict] = []
    ids: set[str] = set()
    for path in paths:
        value = json.loads(path.read_text(encoding="utf-8"))
        cycle_id = value.get("cycle_id")
        if value.get("status") in {"ABORTED_BEFORE_GREEN", "TDD_CYCLE_ABORTED"}:
            if (
                value.get("schema") != 1
                or not isinstance(cycle_id, str)
                or not cycle_id.strip()
                or not isinstance(value.get("reason"), str)
                or not value["reason"].strip()
            ):
                raise RuntimeError(f"invalid aborted TDD provenance: {path}")
            aborted.append({"cycle_id": cycle_id, "reason": value["reason"], "file": path.name})
            continue
        if (
            value.get("schema") != 1
            or not isinstance(cycle_id, str)
            or cycle_id in ids
            or value.get("status") != "GREEN"
            or value.get("mode") not in {"RED_REQUIRED", "CHARACTERIZATION_REQUIRED", "NON_BEHAVIORAL_TEST_FIRST"}
            or not re.fullmatch(r"[0-9a-f]{64}", str(value.get("test_contract_sha256", "")))
            or value.get("test_contract_sha256") != value.get("oracle_sha256")
            or not isinstance(value.get("red"), dict)
            or not isinstance(value.get("green"), dict)
            or not value["red"].get("command")
            or not value["green"].get("command")
            or not re.fullmatch(r"[0-9a-f]{64}", str(value["green"].get("implementation_sha256", "")))
        ):
            raise RuntimeError(f"invalid or incomplete TDD provenance: {path}")
        ids.add(cycle_id)
        cycles.append(value)
    modes = dict(sorted(Counter(cycle["mode"] for cycle in cycles).items()))
    if changed_paths is None and not (root / ".git").exists():
        production = {
            "baseline_revision": None,
            "changed_production_files": None,
            "changed_nonproduction_files": None,
            "digest": None,
            "status": "UNAVAILABLE",
            "justification": "changed-file provenance inventory requires a Git source checkout",
        }
    else:
        production = _validate_production_tdd_map(
            root,
            cycle_ids=ids,
            changed_paths=_git_changed_paths(root) if changed_paths is None else list(changed_paths),
        )
        production["status"] = "PROVEN"
    return {
        "cycle_count": len(cycles),
        "cycle_ids": sorted(ids),
        "modes": modes,
        "digest": canonical_digest(cycles),
        "aborted_count": len(aborted),
        "aborted": aborted,
        "changed_production_files": production["changed_production_files"],
        "changed_nonproduction_files": production["changed_nonproduction_files"],
        "production_map_status": production["status"],
        "production_map_justification": production.get("justification"),
        "production_map_digest": production["digest"],
        "production_map_baseline_revision": production["baseline_revision"],
        "production_changes_without_provenance": 0 if production["status"] == "PROVEN" else None,
    }


def render_traceability(registry: dict) -> str:
    lines = [
        "# Aegis 834-Law Traceability",
        "",
        f"Inventory digest: `{registry['inventory_sha256']}`",
        "",
        f"Exact requirement count: **{registry['requirement_count']}**",
        "",
        "| Requirement | Status | Implementation / stronger property |",
        "|---|---|---|",
    ]
    for item in registry["requirements"]:
        mapped = item.get("subsumed_by") or [item["implemented_test_location"]]
        lines.append(
            f"| `{item['name']}` | {item['status']} | {'<br>'.join(f'`{value}`' for value in mapped)} |"
        )
    return "\n".join(lines) + "\n"


def validate_traceability(root: Path, ledger_path: Path, output_root: Path) -> dict:
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    constitutional = ledger.get("constitutional")
    if (
        ledger.get("requirement_count") != 834
        or ledger.get("outcome") == "FAIL"
        or not isinstance(constitutional, dict)
        or constitutional.get("law_count") != 105
        or not constitutional_report_is_acceptable(constitutional)
    ):
        raise RuntimeError("outer law ledger is incomplete or failed")
    registry = build_traceability(root, ledger_path)
    unfinished = [
        item["name"]
        for item in registry["requirements"]
        if item.get("status") not in FINAL_STATUSES or not item.get("last_result")
    ]
    if unfinished:
        raise RuntimeError(f"traceability contains unfinished requirements: {unfinished[:10]}")
    output_root.mkdir(parents=True, exist_ok=True)
    atomic_write_json(output_root / "traceability-final.json", registry, root=output_root.parents[1], mode=0o600)
    atomic_write_bytes(
        output_root / "traceability-final.md",
        render_traceability(registry).encode("utf-8"),
        root=output_root.parents[1],
        mode=0o600,
    )
    return {
        "requirements": registry["requirement_count"],
        "statuses": dict(sorted(Counter(item["status"] for item in registry["requirements"]).items())),
        "constitutional_laws": constitutional["law_count"],
        "constitutional_counts": constitutional["counts"],
        "inventory_sha256": registry["inventory_sha256"],
    }


def main() -> int:
    root = ROOT.resolve(strict=True)
    python = sys.executable
    initial_governance = capture_governance(root)
    initial_instruction = file_sha256(root / "AGENTS.md")
    static = static_source_validation(root)
    tdd = validate_tdd_provenance(root)
    commands: list[dict] = []
    law_results = root / ".aegis" / "law-results"
    source_ledger = law_results / "release-source.json"

    command_specs = (
        (
            "source-units",
            [python, "-B", "-m", "unittest", "discover", "-s", "infra/tests", "-p", "test_*.py"],
            300.0,
        ),
        (
            "source-properties-standard",
            [python, "-B", "-m", "unittest", "discover", "-s", "infra/property_tests", "-t", "infra", "-p", "test_*.py"],
            900.0,
        ),
        (
            "outer-834-and-constitutional-laws",
            [python, "-B", "infra/law_tests/run_suite.py", "--root", str(root), "--output", str(source_ledger)],
            1200.0,
        ),
        (
            "traceability-meta-laws",
            [python, "-B", "-m", "unittest", "discover", "-s", "infra/law_tests", "-p", "test_meta.py"],
            1200.0,
        ),
        (
            "exact-name-adapters",
            [python, "-B", "-m", "unittest", "discover", "-s", "infra/law_tests", "-p", "test_specification.py"],
            1200.0,
        ),
    )
    for label, argv, timeout in command_specs:
        record, _stdout = execute(label, argv, root, timeout=timeout)
        commands.append(record)
    source_traceability = validate_traceability(root, source_ledger, law_results)

    with tempfile.TemporaryDirectory(prefix="aegis-release-", dir=root) as directory:
        temporary = Path(directory)
        first_root = temporary / "first"
        second_root = temporary / "second"
        first = build_deployment_tree(root, first_root)
        second = build_deployment_tree(root, second_root)
        if (
            first["content_sha256"] != second["content_sha256"]
            or first["manifest_sha256"] != second["manifest_sha256"]
        ):
            raise RuntimeError("source deployment builder is not deterministic")
        for deployed in (first_root, second_root):
            verified = verify_deployment_tree(deployed)
            if not verified["ok"]:
                raise RuntimeError(f"deployment tree verification failed: {verified}")
        # Simulate the separate human-maintainer merge into an existing project.
        # This is a disposable fixture and never invokes an ordinary self-installer.
        (first_root / "AGENTS.md").write_bytes((root / "AGENTS.md").read_bytes())
        manifest_ok, manifest_detail = verify_manifest(first_root, require_release_anchor=True)
        if not manifest_ok:
            raise RuntimeError(f"clean deployment manifest failed: {manifest_detail}")
        clean_ledger = first_root / ".aegis" / "law-results" / "release-clean.json"
        clean_commands = (
            (
                "clean-outer-834-and-constitutional-laws",
                [python, "-B", ".agents/infra/law_tests/run_suite.py", "--root", str(first_root), "--output", str(clean_ledger)],
                1200.0,
            ),
            (
                "clean-units",
                [python, "-B", "-m", "unittest", "discover", "-s", ".agents/infra/tests", "-p", "test_*.py"],
                300.0,
            ),
            (
                "clean-traceability-meta-laws",
                [python, "-B", "-m", "unittest", "discover", "-s", ".agents/infra/law_tests", "-p", "test_meta.py"],
                1200.0,
            ),
        )
        for label, argv, timeout in clean_commands:
            record, _stdout = execute(label, argv, first_root, timeout=timeout)
            commands.append(record)
        clean_traceability = validate_traceability(
            first_root,
            clean_ledger,
            first_root / ".aegis" / "law-results",
        )
        if clean_traceability["statuses"] != source_traceability["statuses"]:
            raise RuntimeError("source and clean deployment traceability outcomes differ")
        clean_issues = audit(first_root)
        if clean_issues:
            raise RuntimeError(f"clean deployment audit failed: {clean_issues}")
        clean_summary = {
            "content_sha256": first["content_sha256"],
            "manifest_sha256": first["manifest_sha256"],
            "file_count": first["file_count"],
            "manifest": manifest_detail,
            "traceability": clean_traceability,
        }

    final_governance = capture_governance(root)
    final_instruction = file_sha256(root / "AGENTS.md")
    if final_governance != initial_governance:
        raise RuntimeError("active .agents or governing instruction snapshot changed during verification")
    if final_instruction != initial_instruction:
        raise RuntimeError("root AGENTS.md changed during verification")

    expected_workspace = workspace_fingerprint(root)
    current_workspace = workspace_fingerprint(root)
    if not expected_workspace.get("available") or not current_workspace.get("available"):
        raise RuntimeError("final workspace fingerprint is unavailable")
    evidence_material = {
        "static": static,
        "tdd": tdd,
        "commands": commands,
        "source_traceability": source_traceability,
        "clean_room": clean_summary,
        "governance_digest": final_governance["digest"],
        "instruction_sha256": final_instruction,
        "workspace_sha256": current_workspace["sha256"],
    }
    evidence_digest = canonical_digest(evidence_material)
    observations = [
        seal_audit_observation(
            check_id=check_id,
            status="PROVEN",
            evidence_digest=evidence_digest,
            provenance="framework-command",
            detail=(
                f"sealed source/clean-room campaign evidence {evidence_digest}; "
                f"commands={len(commands)}; tdd_cycles={tdd['cycle_count']}; "
                f"backlog={source_traceability['requirements']}; constitutional={source_traceability['constitutional_laws']}"
            ),
        )
        for check_id in REQUIRED_FINAL_AUDIT_CHECKS
    ]
    receipt = finalize_audit(
        observations,
        expected_workspace_digest=expected_workspace["sha256"],
        current_workspace_digest=current_workspace["sha256"],
    )
    report = {
        "schema": 1,
        "ok": True,
        "source_root": str(root),
        "static": static,
        "tdd": tdd,
        "source_traceability": source_traceability,
        "clean_room": clean_summary,
        "active_governance_digest": final_governance["digest"],
        "governing_instruction_sha256": final_instruction,
        "workspace_sha256": current_workspace["sha256"],
        "commands": commands,
        "final_audit": receipt,
    }
    destination = root / ".aegis" / "audit" / "final-release-audit.json"
    atomic_write_json(destination, report, root=root, mode=0o600)
    print(json.dumps({"ok": True, "output": str(destination), **{key: report[key] for key in ("active_governance_digest", "governing_instruction_sha256", "workspace_sha256")}, "tdd": tdd, "source_traceability": source_traceability, "clean_room": clean_summary, "final_audit": {"outcome": receipt["outcome"], "check_count": receipt["check_count"], "receipt_sha256": receipt["receipt_sha256"]}}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
