apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
spec:
  parentRefs:
    - name: public-web
      namespace: eve-trade-gateway
      sectionName: https
  hostnames:
    - api.eve-trade.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /eve.api_gateway.v1.GameTradeGatewayService/
      timeouts:
        request: 20s
        backendRequest: 15s
      backendRefs:
        - name: api-gateway
          port: 8080
