apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: eve-trade-default
spec:
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 10
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: encore-backend-high-value
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: encore-backend
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: trade-settlement-high-value
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trade-settlement
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
