apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: eve-trade-strict-mtls
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-encore-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: encore-backend
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/eve-trade/sa/quilkin
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
      to:
        - operation:
            ports:
              - "4000"
              - "26000"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-trade-settlement
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trade-settlement
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/eve-trade/sa/encore-backend
      to:
        - operation:
            ports:
              - "9092"
