apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: encore-backend
spec:
  host: encore-backend.eve-trade.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 2048
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 1000
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: trade-settlement
spec:
  host: trade-settlement.eve-trade.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 512
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nsqd
spec:
  host: nsqd.eve-trade.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 512
