apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eve-trade

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/environment: production

resources:
  - ../../base
  - horizontalpodautoscalers.yaml
  - httproute-redirect.yaml
  - istio-security.yaml
  - istio-telemetry.yaml
  - istio-traffic.yaml
  - networkpolicies.yaml
  - nsq-client-proxy.yaml
  - poddisruptionbudgets.yaml
  - quilkin.yaml
  - resource-governance.yaml

patches:
  - path: patches/namespace.yaml
  - path: patches/configmaps.yaml
  - path: patches/deployments.yaml
  - path: patches/nsq.yaml
