apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: encore-backend-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: encore-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: quilkin
      ports:
        - port: 26000
          protocol: UDP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - port: 4000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: encore-backend-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: encore-backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nsqd
      ports:
        - port: 4150
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trade-settlement
      ports:
        - port: 9092
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: eve-trade-observability
      ports:
        - port: 4318
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nsqd-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nsqd
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: encore-backend
      ports:
        - port: 4150
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trade-settlement-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trade-settlement
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: encore-backend
      ports:
        - port: 9092
          protocol: TCP
