apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: encore-backend
  labels:
    app.kubernetes.io/name: encore-backend
    app.kubernetes.io/component: backend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: encore-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trade-settlement
  labels:
    app.kubernetes.io/name: trade-settlement
    app.kubernetes.io/component: settlement
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trade-settlement
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nsqd
  labels:
    app.kubernetes.io/name: nsqd
    app.kubernetes.io/component: pubsub
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nsqd
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quilkin
  labels:
    app.kubernetes.io/name: quilkin
    app.kubernetes.io/component: udp-proxy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quilkin
