"""Canonical real-deployment prerequisite scenarios.

Selectors are deliberately ordered from the narrowest prerequisite contract to
the broadest.  They classify names only; they never define a business oracle.
"""
from __future__ import annotations

import re
from dataclasses import dataclass


ANYSYSTEM_REVISION = "74613a368c73fb12f25778ce33ca11c9a833da96"
IMPLEMENTED_PENDING = "IMPLEMENTED_BUT_EMULATION_VERIFICATION_PENDING"
PLANNED = "PLANNED"


@dataclass(frozen=True)
class ScenarioDefinition:
    scenario_id: str
    purpose: str
    selectors: tuple[str, ...]
    status: str
    deployed_components: tuple[str, ...]
    workload: str
    action_kind: str
    target: str
    affected_path: str
    activation_barrier: str
    independent_witness: str
    release_barrier: str
    uses_litmus: bool = False
    litmus_experiment: str | None = None
    application_clock_mode: str = "REAL_UNINJECTED"
    blocker: str | None = None
    exclusions: tuple[str, ...] = ()

    def matches(self, name: str) -> bool:
        return any(re.search(pattern, name) for pattern in self.selectors) and not any(
            re.search(pattern, name) for pattern in self.exclusions
        )


SCENARIOS: tuple[ScenarioDefinition, ...] = (
    ScenarioDefinition(
        "database_backup_restore_recovery",
        "Restore a real PostgreSQL snapshot at a declared commit boundary and reconnect the deployment.",
        (r"database_restore", r"restored_database", r"restore_to_point", r"documented_restore_baseline"),
        PLANNED,
        ("postgres", "encore-backend", "trade-settlement", "settlement-worker", "nsqd"),
        "restore-boundary status and replay workload",
        "EXTERNAL_DATABASE_RESTORE",
        "postgres primary",
        "application-to-restored-postgres",
        "backup identity and requested restore point are recorded",
        "independent SQL probe observes the restored timeline and exact recovery point",
        "all application pools reconnect and authoritative state is queryable",
        blocker="A real point-in-time restore provider/backup artifact is not available in the local Kind topology.",
    ),
    ScenarioDefinition(
        "database_primary_failover",
        "Trigger a real database primary failover around a declared transaction boundary.",
        (r"primary_failover", r"new_primary", r"demoted_primary", r"failover_during"),
        PLANNED,
        ("postgres-ha", "encore-backend", "trade-settlement", "settlement-worker"),
        "transaction and idempotent recovery workload",
        "EXTERNAL_DATABASE_FAILOVER",
        "postgres primary",
        "application-to-postgres-primary",
        "transaction boundary and original primary identity are observed",
        "independent SQL topology probe observes a different writable primary",
        "clients discard the demoted connection and reach the new primary",
        blocker="The repository Kind deployment is single-primary PostgreSQL and has no failover control plane.",
    ),
    ScenarioDefinition(
        "rolling_cross_version_compatibility",
        "Run immediately previous and current real binaries concurrently during a controlled rollout.",
        (r"immediately_previous.*concurrently", r"previous_deployed_binary_during_rollout", r"rollback_to_previous_binary"),
        PLANNED,
        ("encore-backend", "trade-settlement", "settlement-worker", "postgres", "nsqd"),
        "cross-version contract workload",
        "DAGGER_ROLLING_VERSION_CHANGE",
        "selected application deployment",
        "versioned producer-consumer path",
        "both immutable image digests are ready in the same namespace",
        "Kubernetes pod image IDs and application build-info endpoints identify both versions",
        "rollout or rollback reaches its declared replica set",
        blocker="No repository-authoritative immediately-previous image digest is pinned for this checkout.",
    ),
    ScenarioDefinition(
        "migration_backfill_restart",
        "Interrupt an identified migration backfill after a durable checkpoint and resume the same real migration.",
        (r"backfill_restart_resumes_without_duplicating_audit_or_outbox_rows",),
        PLANNED,
        ("postgres",),
        "version-bound pre-migration fixture containing multiple backfill batches",
        "DAGGER_RESTART_MIGRATION_AT_BACKFILL_BARRIER",
        "settlement database migration job",
        "migration-job-to-postgres",
        "the exact durable backfill checkpoint and remaining source rows are independently observed",
        "Kubernetes job identity and SQL checkpoint/output rows prove interruption at that boundary",
        "the same migration revision completes and every source row has one required derived row",
        blocker=(
            "The current migration job executes forward-only SQL files without a restartable batch checkpoint "
            "or an observable production-disabled backfill barrier."
        ),
    ),
    ScenarioDefinition(
        "gateway_crash_at_handoff_boundary",
        "Terminate the gateway at one declared handoff boundary selected by the consuming contract.",
        (
            r"gateway_crash_(?:after|before)",
            r"gateway_restart_after_crash_with_reserved_replay",
            r"gateway_worker_panic_does_not_permanently_reduce_worker_capacity",
        ),
        PLANNED,
        ("quilkin", "encore-backend", "postgres"),
        "authenticated UDP request and same-identity replay",
        "LITMUS_CONTAINER_KILL_AT_FAILPOINT",
        "gateway container",
        "quilkin-to-gateway-to-market handoff",
        "production-disabled gateway failpoint confirms the exact named boundary",
        "Kubernetes observes the old container exit after failpoint confirmation",
        "replacement gateway is ready and replay lookup is observable",
        True,
        "container-kill",
        blocker="The gateway exposes no production-disabled persistence/handoff failpoints for exact boundary synchronization.",
    ),
    ScenarioDefinition(
        "gateway_to_market_internal_link_disruption",
        "Disrupt the logical Gateway-to-Market call boundary without pretending that co-located modules have a network edge.",
        (r"gateway_to_market_network_partition_returns_no_false_business_success",),
        PLANNED,
        ("encore-backend", "postgres"),
        "identified authenticated gateway request and durable Market status probe",
        "APPLICATION_INTERNAL_DEPENDENCY_FAILPOINT",
        "Gateway-to-Market call boundary inside encore-backend",
        "gateway-to-market in-process call",
        "gateway request reaches the exact pre-Market-call boundary",
        "application boundary observation proves the Market call is unavailable while the process stays live",
        "the failpoint is absent and a control Gateway-to-Market request succeeds",
        blocker=(
            "Gateway and Market are co-located in the Encore process, so no physical network partition exists; "
            "the repository also has no production-disabled boundary failpoint for this call."
        ),
    ),
    ScenarioDefinition(
        "market_crash_at_persistence_publish_boundary",
        "Terminate Market at a declared durable-operation/outbox/publish boundary.",
        (r"market_crash_(?:after|before)",),
        PLANNED,
        ("encore-backend", "postgres", "nsqd", "settlement-worker"),
        "market operation and idempotent status workload",
        "LITMUS_CONTAINER_KILL_AT_FAILPOINT",
        "market process in encore-backend",
        "market-to-postgres-to-nsqd",
        "production-disabled Market failpoint confirms the exact named boundary",
        "Kubernetes process identity changes after the confirmed boundary",
        "Market is ready and durable operation/outbox state is observable",
        True,
        "container-kill",
        blocker="Market and Gateway share the Encore process and Market has no exact boundary failpoints.",
    ),
    ScenarioDefinition(
        "worker_crash_at_processing_boundary",
        "Terminate a settlement worker at a declared receive/lease/gRPC/publish/ack boundary.",
        (
            r"worker_crash_(?:after|before|during)",
            r"worker_replica_crash_transfers",
            r"restart_after_unclean_shutdown_recovers_every_stale_processing_lease",
        ),
        PLANNED,
        ("settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "settlement work message and idempotent recovery workload",
        "LITMUS_CONTAINER_KILL_AT_FAILPOINT",
        "encore-backend container hosting the settlement-worker service",
        "nsqd-to-worker-to-trade-settlement",
        "production-disabled worker failpoint confirms the named boundary",
        "Kubernetes observes the selected container terminate and message remains independently visible",
        "another worker owns or completes the operation and the channel drains",
        True,
        "container-kill",
        blocker="The worker has no exact boundary failpoints for receive/lease/gRPC/publish/ack phases.",
    ),
    ScenarioDefinition(
        "settlement_crash_at_transaction_boundary",
        "Terminate trade-settlement at a declared transaction/idempotency/outbox boundary.",
        (r"settlement_(?:service_)?crash_(?:after|before)", r"settlement_task_panic_before_commit"),
        PLANNED,
        ("trade-settlement", "postgres", "settlement-worker"),
        "settlement request and status recovery workload",
        "LITMUS_CONTAINER_KILL_AT_FAILPOINT",
        "trade-settlement container",
        "worker-to-settlement-to-postgres",
        "production-disabled settlement failpoint confirms the named transaction boundary",
        "Kubernetes observes container termination after the confirmed boundary",
        "settlement is ready and idempotency-key status is independently queryable",
        True,
        "container-kill",
        blocker="Trade-settlement has no production-disabled transaction-boundary failpoints.",
    ),
    ScenarioDefinition(
        "outbox_dispatcher_crash_at_publish_boundary",
        "Terminate the outbox dispatcher before publish or after publish before durable acknowledgement.",
        (
            r"outbox_dispatcher_recovers_crash",
            r"stale_outbox_claim_is_recovered",
            r"outbox_dispatcher_retries_unpublished_record_after_restart",
            r"outbox_dispatcher_restart_preserves_retry_attempt_metadata",
        ),
        PLANNED,
        ("settlement-worker", "postgres", "nsqd"),
        "committed outbox event and result-consumer workload",
        "LITMUS_CONTAINER_KILL_AT_FAILPOINT",
        "outbox dispatcher container",
        "postgres-outbox-to-nsqd",
        "dispatcher failpoint confirms before-publish or after-publish-before-mark boundary",
        "Kubernetes observes dispatcher process loss and SQL probe observes the claim state",
        "dispatcher recovers the claim and the event reaches its terminal published state",
        True,
        "container-kill",
        blocker="The dispatcher has no exact publish-boundary failpoints.",
    ),
    ScenarioDefinition(
        "pubsub_handler_redelivery_boundary",
        "Create a real unacknowledged or duplicate NSQ delivery at a declared handler boundary.",
        (r"handler_(?:failure|cancellation)_(?:after|before)", r"redelivery_during_first_handler", r"redelivery_after_handler_success", r"shutdown_does_not_ack_in_flight_pubsub"),
        PLANNED,
        ("nsqd", "settlement-worker", "trade-settlement", "postgres"),
        "single identified NSQ message and handler workload",
        "WORKER_HANDLER_FAILPOINT_AND_BROKER_REDELIVERY",
        "settlement work channel handler",
        "nsqd-to-settlement-worker",
        "handler failpoint confirms the exact commit/publish/ack boundary",
        "NSQ stats independently show the message in-flight or requeued with the same identity",
        "message is terminally acknowledged or quarantined and the channel is healthy",
        blocker="The worker has no exact handler-boundary failpoints and NSQ test hooks for deterministic redelivery timing.",
    ),
    ScenarioDefinition(
        "cleanup_job_crash_between_batches",
        "Terminate the retention cleanup worker after one committed batch and prove restart resumes at the next eligible set.",
        (r"cleanup_job_crash_between_batches",),
        PLANNED,
        ("postgres", "settlement-worker"),
        "multiple identified retention-eligible batches plus protected control rows",
        "APPLICATION_CLEANUP_BATCH_FAILPOINT",
        "retention cleanup worker between committed batches",
        "cleanup-worker-to-postgres",
        "the first exact cleanup batch is committed and the next eligible row set is observed",
        "application and SQL observations prove the cleanup process stopped at the inter-batch boundary",
        "the cleanup worker restarts, resumes, and leaves protected control rows unchanged",
        blocker=(
            "The local deployment has no independently addressable cleanup worker or production-disabled "
            "inter-batch crash boundary."
        ),
    ),
    ScenarioDefinition(
        "duplicate_message_delivery",
        "Publish the same logical work/result identity more than once through the real broker.",
        (
            r"duplicate_(?:settlement|terminal|outbox|redelivery|delivery)",
            r"same_message_id_with_different_payload",
            r"different_message_ids_with_same_idempotency",
            r"pubsub_redelivery_preserves_idempotency",
            r"random_duplicate_message_injection_during_mixed_trade_workload",
        ),
        IMPLEMENTED_PENDING,
        ("nsqd", "settlement-worker", "trade-settlement", "encore-backend", "postgres"),
        "duplicate identified work or result message",
        "BROKER_PUBLISH_DUPLICATE",
        "declared NSQ topic and channel",
        "publisher-to-nsqd-to-consumer",
        "first delivery identity is observed at the declared consumer boundary",
        "NSQ stats and application message observations record at least two deliveries of the same logical identity",
        "all deliveries reach terminal handling and channel in-flight count returns to baseline",
        exclusions=(
            r"duplicate_delivery_storm",
            r"sustained_duplicate_delivery_load",
            r"duplicate_outbox_publication",
            r"rolling_worker",
            r"loses_grpc_connection",
        ),
    ),
    ScenarioDefinition(
        "poison_message_retry_and_quarantine",
        "Inject one exactly identified poison message ahead of healthy work and observe bounded terminal handling.",
        (r"poison_message", r"poison_work_message", r"outbox_poison_record"),
        IMPLEMENTED_PENDING,
        ("nsqd", "settlement-worker", "postgres"),
        "poison message followed by healthy identified work",
        "BROKER_PUBLISH_POISON_AND_CONTROL",
        "declared correctness-critical NSQ channel",
        "nsqd-to-settlement-worker",
        "poison payload and healthy control payload are durably published in order",
        "broker counters and application logs identify poison redeliveries and later healthy-message processing",
        "poison message reaches declared terminal handling and healthy work completes",
    ),
    ScenarioDefinition(
        "graceful_shutdown_with_inflight_work",
        "Request a real graceful shutdown after identified work becomes queued or in flight.",
        (
            r"gateway_shutdown",
            r"service_shutdown",
            r"shutdown_(?:deadline|marks|waits)",
            r"termination_grace_period",
            r"worker_shutdown_during_(?:processing|idle)",
            r"settlement_shutdown_closes",
        ),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "queued and in-flight identified request/message",
        "DAGGER_GRACEFUL_POD_TERMINATION",
        "scenario-selected application pod",
        "client-or-broker-to-selected-service",
        "request/message identity is observed at the declared queued or in-flight boundary",
        "Kubernetes termination state plus application/broker observations prove drain disposition",
        "replacement is ready and unfinished work is either completed or redeliverable",
    ),
    ScenarioDefinition(
        "rolling_gateway_replica_replacement",
        "Roll gateway replicas while identified UDP requests remain in flight.",
        (
            r"rolling_gateway",
            r"load_balancer_removes_unready_gateway",
            r"rolling_update_max_unavailable_preserves_at_least_one_ready_gateway",
            r"gateway_restart_rebinds_udp_socket",
            r"udp_socket_rebind_after_restart",
            r"rate_limiter_restart_does_not_grant_more_than_documented_burst_capacity",
            r"replay_cache_restart_does_not_weaken_durable_exactly_once_guarantee",
        ),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "authenticated UDP requests with stable idempotency identities",
        "DAGGER_ROLLOUT_RESTART",
        "encore-backend deployment",
        "quilkin-to-gateway",
        "old and new replica identities overlap at the declared rollout phase",
        "Kubernetes EndpointSlice and pod UID observations prove unready routing removal and replacement",
        "rollout completes with required ready replicas",
    ),
    ScenarioDefinition(
        "rolling_market_replica_replacement",
        "Roll Market replicas while a durable operation is awaiting publication.",
        (r"rolling_market", r"market_projection_is_idempotent_across_process_restart"),
        IMPLEMENTED_PENDING,
        ("encore-backend", "postgres", "nsqd"),
        "durably accepted market operation",
        "DAGGER_ROLLOUT_RESTART",
        "encore-backend deployment",
        "market-to-postgres-to-nsqd",
        "durable operation identity exists before old replica termination",
        "pod UID transition and SQL/outbox observations bind the operation across the rollout",
        "rollout completes and operation reaches terminal publication state",
    ),
    ScenarioDefinition(
        "rolling_worker_replica_replacement",
        "Roll worker replicas while identified messages and processing leases exist.",
        (
            r"rolling_worker",
            r"rolling_worker_replica_replacement",
            r"rolling_update_max_unavailable_preserves_at_least_one_ready_worker_replica",
            r"request_attempt_history_survives_worker_restart",
            r"worker_restart_does_not_reexecute_committed_operation",
            r"worker_restart_recovers_processing_operation",
        ),
        IMPLEMENTED_PENDING,
        ("settlement-worker", "nsqd", "trade-settlement", "postgres"),
        "identified settlement message and processing lease",
        "DAGGER_ROLLOUT_RESTART",
        "encore-backend deployment hosting the settlement-worker service",
        "nsqd-to-worker-to-settlement",
        "message or lease identity is observed before old replica termination",
        "pod UID transition, broker stats, and SQL lease observations bind recovery to the new replica",
        "rollout completes and no scenario-owned lease remains stale",
    ),
    ScenarioDefinition(
        "rolling_settlement_replica_replacement",
        "Roll settlement replicas around identified transaction requests.",
        (
            r"rolling_settlement",
            r"worker_returns_to_pre_failure_throughput_slo_after_settlement_service_restart",
        ),
        IMPLEMENTED_PENDING,
        ("trade-settlement", "postgres", "settlement-worker"),
        "identified settlement requests",
        "DAGGER_ROLLOUT_RESTART",
        "trade-settlement deployment",
        "worker-to-settlement-to-postgres",
        "request identity is observed before old replica termination",
        "pod UID transition and SQL transaction/idempotency observations bind the request across rollout",
        "rollout completes and settlement status is queryable",
    ),
    ScenarioDefinition(
        "gateway_pod_delete_during_udp_workload",
        "Delete one selected gateway pod while authenticated UDP requests cross the fault window.",
        (r"pod_deletion_during_udp_load",),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "authenticated UDP issue/accept/cancel requests",
        "LITMUS_POD_DELETE",
        "encore-backend pod selected by exact labels and UID",
        "quilkin-to-gateway",
        "workload request is observed at the selected gateway before deletion",
        "Litmus acknowledgement and Kubernetes old-pod UID disappearance/replacement are both required",
        "replacement pod is ready and UDP control probe succeeds",
        True,
        "pod-delete",
    ),
    ScenarioDefinition(
        "worker_pod_delete_during_message_processing",
        "Delete one selected worker pod after an identified message enters processing.",
        (r"worker_pod_deletion_during_message_processing",),
        IMPLEMENTED_PENDING,
        ("nsqd", "settlement-worker", "trade-settlement", "postgres"),
        "identified settlement work message",
        "LITMUS_POD_DELETE",
        "encore-backend pod hosting settlement-worker, selected by exact labels and UID",
        "nsqd-to-worker-to-settlement",
        "application/SQL witness observes the message processing owner",
        "Litmus acknowledgement, Kubernetes UID loss, and broker in-flight transition prove the effect",
        "replacement worker is ready and the message is no longer permanently in flight",
        True,
        "pod-delete",
    ),
    ScenarioDefinition(
        "settlement_pod_delete_during_database_transaction",
        "Delete one selected settlement pod while its identified database transaction is open.",
        (r"trade_settlement_pod_deletion_during_database_transaction",),
        PLANNED,
        ("trade-settlement", "postgres", "settlement-worker"),
        "identified multi-operation settlement request",
        "LITMUS_POD_DELETE_AT_TRANSACTION_BARRIER",
        "trade-settlement pod selected by exact labels and UID",
        "settlement-to-postgres",
        "production-disabled transaction barrier confirms the transaction is open before commit",
        "Litmus acknowledgement, Kubernetes UID loss, and independent pg_stat_activity observation prove overlap",
        "replacement settlement pod is ready and transaction/idempotency state is queryable",
        True,
        "pod-delete",
        blocker="No safe application transaction barrier exposes the exact open-transaction window.",
    ),
    ScenarioDefinition(
        "gateway_single_node_drain",
        "Drain the node hosting one gateway replica while the control replica remains routable.",
        (r"single_node_drain_does_not_make_all_gateway",),
        PLANNED,
        ("quilkin", "encore-backend"),
        "continuous authenticated UDP control workload",
        "LITMUS_NODE_DRAIN",
        "node hosting a selected encore-backend pod",
        "quilkin-to-gateway replicas",
        "selected pod/node and unaffected replica are both ready",
        "Litmus acknowledgement, node unschedulable state, and selected pod relocation are required",
        "replacement topology satisfies the registered minimum-ready condition",
        True,
        "node-drain",
        blocker=(
            "The Dagger Kind topology currently has one control-plane node and the local overlay has one "
            "gateway replica, so it cannot establish a drain while an unaffected replica remains routable."
        ),
    ),
    ScenarioDefinition(
        "worker_single_node_drain",
        "Drain the node hosting one worker replica while identified work remains recoverable.",
        (r"single_node_drain_does_not_make_all_settlement_worker",),
        PLANNED,
        ("settlement-worker", "nsqd", "trade-settlement"),
        "identified settlement message plus healthy control message",
        "LITMUS_NODE_DRAIN",
        "node hosting a selected encore-backend pod that runs settlement-worker",
        "nsqd-to-worker replicas",
        "selected worker/node and unaffected worker are ready",
        "Litmus acknowledgement, node unschedulable state, pod relocation, and broker state prove the effect",
        "replacement topology is ready and scenario-owned messages leave in-flight state",
        True,
        "node-drain",
        blocker=(
            "The Dagger Kind topology currently has one control-plane node and the local overlay has one "
            "encore-backend replica hosting the worker, so no unaffected worker can remain during a drain."
        ),
    ),
    ScenarioDefinition(
        "market_to_pubsub_directional_partition",
        "Block the declared Market-to-NSQ path after durable operation persistence.",
        (r"market_to_pubsub_network_partition", r"pubsub_broker_unavailable_during_market_publish"),
        IMPLEMENTED_PENDING,
        ("encore-backend", "postgres", "nsqd", "settlement-worker"),
        "durably accepted market operation",
        "LITMUS_DIRECTIONAL_NETWORK_PARTITION",
        "encore-backend egress to nsqd",
        "market-to-nsqd",
        "SQL witness observes the durable operation/outbox row before activation",
        "Litmus acknowledgement and independent source-to-destination network probe failure are required",
        "partition is absent, probe succeeds, and durable operation reaches broker",
        True,
        "pod-network-partition",
    ),
    ScenarioDefinition(
        "worker_to_settlement_directional_partition",
        "Block worker-to-settlement requests while preserving broker delivery and status evidence.",
        (r"worker_to_settlement_network_partition",),
        IMPLEMENTED_PENDING,
        ("nsqd", "settlement-worker", "trade-settlement", "postgres"),
        "identified settlement work message",
        "LITMUS_DIRECTIONAL_NETWORK_PARTITION",
        "encore-backend pod egress from settlement-worker to trade-settlement",
        "worker-to-trade-settlement",
        "worker observes the identified work message before activation",
        "Litmus acknowledgement and independent worker-origin gRPC reachability probe failure are required",
        "partition is absent, gRPC probe succeeds, and message reaches terminal handling",
        True,
        "pod-network-partition",
    ),
    ScenarioDefinition(
        "settlement_to_postgres_unknown_commit_partition",
        "Partition settlement-to-PostgreSQL at a declared before-commit or after-commit-ack-loss phase.",
        (r"settlement_to_postgres_network_partition", r"postgres_connection_failure_after_commit_ack_loss"),
        PLANNED,
        ("trade-settlement", "postgres", "settlement-worker"),
        "identified settlement request and idempotency status lookup",
        "LITMUS_DIRECTIONAL_NETWORK_PARTITION_AT_TRANSACTION_BARRIER",
        "trade-settlement egress to postgres",
        "settlement-to-postgres",
        "transaction boundary failpoint confirms before-commit or after-commit state",
        "Litmus acknowledgement and independent settlement-origin PostgreSQL probe failure are required",
        "partition is absent, SQL probe succeeds, and idempotency status is queryable",
        True,
        "pod-network-partition",
        blocker="No safe transaction barrier distinguishes before-commit from after-commit acknowledgement loss.",
    ),
    ScenarioDefinition(
        "asymmetric_response_path_partition",
        "Permit requests on a declared path while blocking the corresponding response direction.",
        (r"asymmetric_partition_where_requests_arrive_but_responses_are_lost",),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "identified idempotent request and replay",
        "LITMUS_DIRECTIONAL_NETWORK_PARTITION",
        "scenario-selected response path",
        "declared request/response service edge",
        "request identity is observed at the destination before response-path activation",
        "Litmus acknowledgement plus directional probes prove request success and response failure",
        "both directional probes succeed and status/replay path is available",
        True,
        "pod-network-partition",
    ),
    ScenarioDefinition(
        "quilkin_gateway_packet_duplication",
        "Duplicate packets only on the declared Quilkin-to-gateway UDP path.",
        (r"packet_duplication_between_quilkin_and_gateway",),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "sequence-numbered authenticated UDP requests",
        "LITMUS_NETWORK_DUPLICATION",
        "quilkin egress to encore-backend UDP",
        "quilkin-to-gateway",
        "clean sequence-numbered UDP control exchange is observed",
        "Litmus acknowledgement and independent UDP sequence probe observes duplicate datagrams",
        "duplication qdisc is absent and clean control exchange succeeds",
        True,
        "pod-network-duplication",
    ),
    ScenarioDefinition(
        "mixed_workload_network_delay",
        "Add declared latency to one real service path during mixed trade workload.",
        (r"random_network_delay_during_mixed_trade_workload", r"litmus_network_delay_experiment"),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "mixed issue/accept/cancel workload with stable identities",
        "LITMUS_NETWORK_LATENCY",
        "scenario-selected application path",
        "declared source-to-destination service edge",
        "clean baseline latency distribution is recorded",
        "Litmus acknowledgement and independent probe observes latency above the generated lower bound",
        "latency qdisc is absent and recovered probe returns within the bounded control envelope",
        True,
        "pod-network-latency",
    ),
    ScenarioDefinition(
        "targeted_network_loss",
        "Apply declared packet loss to one selected service path during identified workload.",
        (r"litmus_network_loss_experiment",),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "sequence-numbered path-specific control and business workload",
        "LITMUS_NETWORK_LOSS",
        "scenario-selected source pod and destination",
        "declared service edge",
        "clean control probe batch has zero observed loss",
        "Litmus acknowledgement and independent sequence probe observes loss within declared tolerance",
        "loss qdisc is absent and recovered probe batch succeeds",
        True,
        "pod-network-loss",
    ),
    ScenarioDefinition(
        "settlement_dns_resolution_failure",
        "Make only the worker's declared settlement hostname resolution fail.",
        (r"dns_resolution_failure_for_settlement_endpoint",),
        IMPLEMENTED_PENDING,
        ("settlement-worker", "trade-settlement", "nsqd"),
        "identified settlement work message",
        "LITMUS_DNS_ERROR",
        "settlement-worker DNS lookup for trade-settlement service",
        "worker-to-cluster-dns-to-settlement",
        "worker-origin control lookup resolves the exact service name",
        "Litmus acknowledgement and independent worker-origin DNS probe observes the declared failure",
        "DNS fault is absent, lookup resolves, and work message reaches terminal handling",
        True,
        "pod-dns-error",
    ),
    ScenarioDefinition(
        "gateway_cpu_pressure",
        "Apply generated CPU pressure to one gateway replica while a control replica remains measurable.",
        (r"cpu_saturation_does_not_violate",),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "authenticated duplicate/replay workload plus unaffected-replica control",
        "LITMUS_CPU_HOG",
        "selected encore-backend pod",
        "quilkin-to-selected-gateway",
        "selected and control replica identities plus CPU baseline are recorded",
        "Litmus acknowledgement and independent container CPU metric cross the declared threshold",
        "CPU stress is absent and selected replica returns to readiness",
        True,
        "pod-cpu-hog",
    ),
    ScenarioDefinition(
        "gateway_memory_pressure",
        "Apply bounded memory pressure to one gateway replica during overload workload.",
        (r"gateway_under_memory_pressure",),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "authenticated overload workload",
        "LITMUS_MEMORY_HOG",
        "selected encore-backend pod",
        "quilkin-to-selected-gateway",
        "selected pod identity and memory baseline are recorded",
        "Litmus acknowledgement and independent working-set probe observe declared pressure",
        "memory stress is absent and gateway is ready",
        True,
        "pod-memory-hog",
    ),
    ScenarioDefinition(
        "worker_memory_pressure",
        "Apply bounded memory pressure to one worker while identified messages remain recoverable.",
        (r"worker_under_memory_pressure",),
        IMPLEMENTED_PENDING,
        ("settlement-worker", "nsqd", "trade-settlement"),
        "identified settlement work and healthy control message",
        "LITMUS_MEMORY_HOG",
        "selected encore-backend pod hosting settlement-worker",
        "nsqd-to-selected-worker",
        "selected pod identity, broker baseline, and memory baseline are recorded",
        "Litmus acknowledgement and independent working-set probe observe declared pressure",
        "memory stress is absent, worker is ready, and unfinished messages are recoverable",
        True,
        "pod-memory-hog",
    ),
    ScenarioDefinition(
        "postgres_disk_full_during_commit",
        "Fill the PostgreSQL data filesystem to a bounded threshold during an identified commit attempt.",
        (r"disk_full_during_postgres_commit",),
        PLANNED,
        ("trade-settlement", "postgres"),
        "identified settlement transaction",
        "LITMUS_DISK_FILL_AT_TRANSACTION_BARRIER",
        "postgres data filesystem",
        "settlement-to-postgres",
        "transaction failpoint confirms the pre-commit phase",
        "Litmus acknowledgement and independent filesystem probe observe declared utilization",
        "fill files are removed, filesystem is writable, and PostgreSQL is ready",
        True,
        "disk-fill",
        blocker="No safe transaction barrier synchronizes disk fill with the exact PostgreSQL commit window.",
    ),
    ScenarioDefinition(
        "application_logging_disk_full",
        "Fill only the selected application's log filesystem during an identified committed request.",
        (r"disk_full_during_application_logging",),
        IMPLEMENTED_PENDING,
        ("encore-backend", "postgres"),
        "identified request with durable status lookup",
        "LITMUS_DISK_FILL",
        "encore-backend log filesystem",
        "application-to-log-sink",
        "application log path and clean filesystem baseline are observed",
        "Litmus acknowledgement and independent filesystem probe observe declared utilization",
        "fill files are removed and application readiness is restored",
        True,
        "disk-fill",
    ),
    ScenarioDefinition(
        "postgres_restart_during_settlement",
        "Replace the PostgreSQL pod while an identified settlement request is active.",
        (r"postgres_restart_during_settlement",),
        IMPLEMENTED_PENDING,
        ("trade-settlement", "postgres", "settlement-worker"),
        "identified settlement request and status recovery",
        "LITMUS_POD_DELETE",
        "postgres pod selected by exact labels and UID",
        "settlement-to-postgres",
        "request identity and original PostgreSQL pod UID are recorded",
        "Litmus acknowledgement and Kubernetes old-pod UID disappearance/replacement are required",
        "replacement PostgreSQL is ready and status query succeeds",
        True,
        "pod-delete",
    ),
    ScenarioDefinition(
        "nsq_restart_during_delivery",
        "Replace the NSQ pod while an identified message is pending or in flight.",
        (r"nsq(?:d)?_restart", r"pubsub_broker_restart"),
        IMPLEMENTED_PENDING,
        ("nsqd", "settlement-worker", "encore-backend", "postgres"),
        "identified pending or in-flight NSQ message",
        "LITMUS_POD_DELETE",
        "nsqd pod selected by exact labels and UID",
        "publisher-to-nsqd-to-consumer",
        "broker stats observe the message and original nsqd UID",
        "Litmus acknowledgement and Kubernetes old-pod UID disappearance/replacement are required",
        "replacement nsqd is ready and message terminal state is observable",
        True,
        "pod-delete",
    ),
    ScenarioDefinition(
        "random_service_kill_mixed_workload",
        "Use the AnySystem seed to choose a declared service-kill point during mixed trade workload.",
        (r"random_service_kill_during_mixed_trade_workload", r"process_sigkill_at_each_persistence_boundary"),
        PLANNED,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "mixed issue/accept/cancel workload with stable identities",
        "LITMUS_CONTAINER_KILL_AT_DECLARED_BOUNDARY",
        "seed-selected member of the scenario allowlist",
        "seed-selected persistence boundary",
        "production-disabled failpoint confirms the seed-selected boundary",
        "Litmus acknowledgement and Kubernetes container identity transition prove the exact kill",
        "selected component is ready and all scenario-owned operations are terminal or retryable",
        True,
        "container-kill",
        blocker="The required persistence-boundary failpoints are not present across all seed-selectable services.",
    ),
    ScenarioDefinition(
        "random_crash_restart_sequence",
        "Replay a seeded allowlisted sequence of real pod deletions and recovery barriers.",
        (r"random_crash_and_restart_sequence", r"reconciliation_holds_after_random_crash_restart"),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "identified trade workload spanning seeded crash steps",
        "LITMUS_SEEDED_POD_DELETE_SEQUENCE",
        "seed-selected pods from the explicit scenario allowlist",
        "seed-selected application path",
        "controller trace records selected target and ready-state barrier before each deletion",
        "each Litmus acknowledgement is paired with Kubernetes UID disappearance/replacement evidence",
        "every selected component passes its declared recovery barrier before the next logical tick",
        True,
        "pod-delete",
    ),
    ScenarioDefinition(
        "dependency_outage_backlog_and_recovery",
        "Make one declared required dependency unavailable, accumulate identified work, then recover it.",
        (
            r"pubsub_backlog_recovers_after_downstream_pause",
            r"readiness_endpoint_fails_while_required_dependency",
            r"health_endpoint_does_not_report_ready_when_(?:postgres|required_pubsub)",
            r"liveness_endpoint_stays_successful_during_recoverable_downstream_outage",
            r"quilkin_backend_unavailable_returns_no_false_success",
        ),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "identified workload plus readiness/liveness probes",
        "DAGGER_SCALE_DEPENDENCY_TO_ZERO",
        "scenario-declared postgres, nsqd, or settlement dependency",
        "declared service dependency edge",
        "clean dependency and service-health baselines are observed",
        "Kubernetes zero-ready state and independent path probe prove unavailability",
        "dependency and application readiness recover and scenario-owned backlog drains",
    ),
    ScenarioDefinition(
        "database_connection_failure_window",
        "Disrupt real PostgreSQL connections before begin or during an active request and restore connectivity.",
        (
            r"database_connection_loss_(?:after|before)",
            r"database_connection_pool_exhaustion",
            r"half_open_postgres_connection",
            r"postgres_connection_failure_before_begin",
            r"random_postgres_disconnects_during_mixed_trade_workload",
            r"settlement_under_database_connection_pressure",
        ),
        IMPLEMENTED_PENDING,
        ("trade-settlement", "postgres", "encore-backend"),
        "identified database-backed request and connection-pool probes",
        "LITMUS_NETWORK_PARTITION",
        "application egress to postgres",
        "application-to-postgres",
        "clean SQL probe and declared request phase are observed",
        "Litmus acknowledgement and independent application-origin SQL probe failure are required",
        "partition is absent, SQL probe succeeds, and pool capacity returns to baseline",
        True,
        "pod-network-partition",
    ),
    ScenarioDefinition(
        "grpc_connection_failure_window",
        "Disrupt a real worker-to-settlement gRPC connection at a declared write/commit uncertainty phase.",
        (
            r"half_open_grpc_connection",
            r"worker_grpc_connection_failure_before_request_write",
            r"worker_loses_grpc_connection",
            r"grpc_deadline_exceeded_after_possible_commit",
            r"grpc_deadline_exceeded_with_unknown_commit_outcome",
            r"grpc_unavailable_before_request_write",
            r"transient_grpc_unavailable",
        ),
        PLANNED,
        ("settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "identified gRPC request and status recovery",
        "LITMUS_DIRECTIONAL_NETWORK_PARTITION_AT_GRPC_BARRIER",
        "worker egress to trade-settlement",
        "worker-to-settlement",
        "gRPC transport failpoint distinguishes before-write from possible-commit phase",
        "Litmus acknowledgement and independent worker-origin gRPC probe failure are required",
        "partition is absent and idempotency status lookup succeeds",
        True,
        "pod-network-partition",
        blocker="No transport barrier exposes before-write versus possible-commit phases to the scenario controller.",
    ),
    ScenarioDefinition(
        "trade_terminal_accept_cancel_race",
        "Release accept and cancel contenders at the same real transaction race barrier.",
        (r"accept_and_cancel_transactions", r"accept_racing_with_retry_of_successful_cancel", r"cancel_racing_with_retry_of_successful_accept", r"concurrent_full_accept_and_cancel", r"two_full_accepts_and_cancel", r"partial_accept_and_cancel_race", r"multiple_partial_accepts_and_cancel_race"),
        PLANNED,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres"),
        "accept and cancel contenders for one exact trade version",
        "APPLICATION_TRANSACTION_RACE_BARRIER",
        "trade row/version",
        "concurrent settlement transactions",
        "all contenders report arrival immediately before the target commit race",
        "independent pg_stat_activity/lock probe identifies both exact contender transactions",
        "all contenders finish and no scenario-owned transaction remains open",
        blocker="The real settlement path has no production-disabled commit-race barrier.",
    ),
    ScenarioDefinition(
        "concurrent_accept_quantity_race",
        "Release multiple accept contenders after reading the same exact remaining quantity.",
        (
            r"concurrent_accepts",
            r"concurrent_partial_accepts",
            r"two_accept_transactions",
            r"same_buyer_concurrent_partial_accepts",
            r"different_buyers_cannot_write_partial_fills",
            r"different_trades_concurrently_crediting_same_destination_stack",
        ),
        PLANNED,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres"),
        "multiple accept requests for one exact trade version",
        "APPLICATION_TRANSACTION_RACE_BARRIER",
        "trade and item-escrow rows",
        "concurrent accept transactions",
        "all contenders report the same pre-mutation trade version/quantity boundary",
        "independent PostgreSQL lock/activity probe identifies every contender",
        "all contenders finish and row locks are released",
        blocker="The real settlement path has no pre-mutation race barrier.",
    ),
    ScenarioDefinition(
        "concurrent_wallet_debit_race",
        "Release wallet debit contenders after observing the same available balance.",
        (r"two_wallet_debits", r"different_trades_concurrently_debiting_same_wallet", r"random_cross_trade_wallet_contention", r"concurrent_requests_to_same_wallet"),
        PLANNED,
        ("settlement-worker", "trade-settlement", "postgres"),
        "multiple settlements sharing one wallet",
        "APPLICATION_TRANSACTION_RACE_BARRIER",
        "wallet row",
        "concurrent wallet-debit transactions",
        "all contenders report arrival before the same wallet mutation boundary",
        "independent PostgreSQL lock/activity probe identifies every contender",
        "all contenders finish and wallet row locks are released",
        blocker="The real settlement path has no wallet pre-mutation race barrier.",
    ),
    ScenarioDefinition(
        "concurrent_item_reservation_race",
        "Release item reservation contenders after observing the same source-stack quantity.",
        (r"two_item_escrow_reservations", r"concurrent_issues_from_same", r"concurrent_issue_and_external_stack_mutation", r"random_cross_trade_stack_contention", r"concurrent_requests_to_same_item_stack"),
        PLANNED,
        ("settlement-worker", "trade-settlement", "postgres"),
        "multiple issue requests sharing one item stack",
        "APPLICATION_TRANSACTION_RACE_BARRIER",
        "source item-stack row",
        "concurrent item-reservation transactions",
        "all contenders report arrival before the same stack mutation boundary",
        "independent PostgreSQL lock/activity probe identifies every contender",
        "all contenders finish and item row locks are released",
        blocker="The real settlement path has no stack pre-mutation race barrier.",
    ),
    ScenarioDefinition(
        "concurrent_idempotency_key_race",
        "Release duplicate/conflicting requests with the same identity against multiple real replicas.",
        (r"concurrent_(?:identical|conflicting)_requests", r"concurrent_insert_of_same_idempotency", r"two_market_replicas_receiving_same_request", r"two_worker_replicas_receiving_duplicate", r"same_authenticated_request_sent_to_two_gateway", r"conflicting_payloads_with_same_idempotency"),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "barrier-released requests sharing one exact idempotency identity",
        "DAGGER_WORKLOAD_BARRIER_RELEASE",
        "multiple selected application replicas",
        "client/broker-to-multiple-replicas",
        "all generated requests are connected and ready at the client-side release barrier",
        "application request observations and SQL connection/activity evidence identify every contender",
        "all request attempts terminate and the barrier-owned clients close",
    ),
    ScenarioDefinition(
        "concurrent_outbox_claim_race",
        "Release multiple outbox dispatchers against the same eligible row/ordered trade stream.",
        (r"concurrent_outbox_dispatchers", r"two_outbox_dispatcher_replicas"),
        PLANNED,
        ("settlement-worker", "postgres", "nsqd"),
        "one eligible outbox row plus dispatcher contenders",
        "APPLICATION_OUTBOX_CLAIM_BARRIER",
        "outbox row or per-trade ordered row set",
        "dispatcher-to-postgres claim",
        "all dispatchers report arrival before claim acquisition",
        "independent PostgreSQL lock/activity probe identifies every dispatcher contender",
        "dispatchers finish and no scenario-owned claim remains stale",
        blocker="The dispatcher has no production-disabled pre-claim barrier.",
    ),
    ScenarioDefinition(
        "cluster_rate_limit_replica_race",
        "Release rate-limit checks concurrently and alternate requests across gateway replicas.",
        (r"concurrent_rate_limit_checks", r"cluster_rate_limit_cannot_be_bypassed", r"alternating_gateway_replicas"),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend"),
        "authenticated requests for one principal plus independent control principal",
        "DAGGER_WORKLOAD_BARRIER_RELEASE",
        "multiple gateway replicas and one logical rate-limit bucket",
        "quilkin-to-gateway replicas",
        "all generated requests are ready at the client-side release barrier",
        "application observations identify principal, replica, and terminal response for every request",
        "all requests terminate and rate-limit observations are collected",
    ),
    ScenarioDefinition(
        "hot_resource_contention_with_control_workload",
        "Sustain contention on one trade/wallet/outbox stream while measuring unrelated control work.",
        (
            r"single_hot_(?:trade|wallet)",
            r"hot_trade_contention",
            r"large_outbox_backlog_for_one_trade",
            r"unrelated_trade.*contention",
            r"accept_of_unrelated_trades_does_not_acquire_conflicting_table_level_lock",
            r"cancel_of_one_trade_does_not_block_accept_of_unrelated_trade",
            r"concurrent_requests_to_same_trade",
        ),
        IMPLEMENTED_PENDING,
        ("encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "hot-resource workload plus unrelated identified control workload",
        "DAGGER_CONCURRENT_WORKLOAD",
        "scenario-selected hot trade, wallet, or outbox stream",
        "application-to-shared-resource and unrelated control path",
        "hot workload reaches declared in-flight/lock/backlog threshold",
        "independent SQL/broker probe observes hot pressure while control identities remain distinct",
        "both workloads complete and pressure metrics return to baseline",
    ),
    ScenarioDefinition(
        "gateway_queue_saturation",
        "Fill the bounded gateway queue while tracking accepted and rejected request identities.",
        (r"gateway_queue_(?:full|saturation|memory)", r"gateway_rejects_new_work_when_bounded_queue", r"gateway_slow_downstream", r"load_shedding_prefers_explicit_backpressure"),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "postgres"),
        "bounded authenticated request burst plus slow downstream control",
        "DAGGER_BOUNDED_LOAD_AND_DEPENDENCY_DELAY",
        "gateway queue and worker pool",
        "quilkin-to-gateway-to-market",
        "independent application metric observes the configured queue capacity boundary",
        "request observations and bounded memory/queue metrics prove saturation",
        "queue drains and capacity returns to baseline",
    ),
    ScenarioDefinition(
        "udp_receive_buffer_saturation",
        "Saturate the real gateway UDP receive buffer while binding kernel drops and application responses to exact datagrams.",
        (r"udp_receive_buffer_saturation_does_not_create_false_success_response",),
        PLANNED,
        ("quilkin", "encore-backend"),
        "sequence-numbered authenticated UDP burst above the observed socket drain rate",
        "DAGGER_UDP_SOCKET_BUFFER_SATURATION",
        "selected gateway UDP socket and host receive queue",
        "quilkin-to-gateway-udp-socket",
        "socket identity, receive-buffer capacity, and clean control exchange are observed",
        "independent kernel socket/drop counters and application receipts identify the saturated interval",
        "receive queue and drop counters stabilize and a clean control exchange succeeds",
        blocker=(
            "The local deployment does not expose a run-scoped kernel socket/drop probe that can bind receive "
            "buffer saturation to the selected gateway socket and exact request identities."
        ),
    ),
    ScenarioDefinition(
        "sustained_mixed_trade_load",
        "Run a bounded mixed issue/accept/cancel burst at declared concurrency and duration.",
        (
            r"(?:authenticated_udp_(?:issue|accept|cancel)|mixed_issue_accept_cancel)_burst",
            r"p99_latency_stays_below",
            r"sustained_duplicate_delivery_load",
            r"duplicate_delivery_storm",
            r"slow_settlement_requests_do_not_consume_every_worker",
            r"one_overloaded_gateway_replica_does_not_make_healthy_replica_return_false_success",
            r"random_concurrent_trade_sequence_preserves_per_trade_state_machine",
        ),
        IMPLEMENTED_PENDING,
        ("quilkin", "encore-backend", "settlement-worker", "trade-settlement", "postgres", "nsqd"),
        "bounded mixed trade load with exact completion target",
        "DAGGER_BOUNDED_LOAD",
        "full deployed request path",
        "quilkin-to-gateway-to-market-to-worker-to-settlement",
        "all workload actors and exact completion target are registered before release",
        "application, database, broker, and resource probes account for every request identity",
        "configured completion target is reached and resource pools return to baseline",
    ),
    ScenarioDefinition(
        "configuration_reload_during_inflight_request",
        "Reload one declared configuration document while an identified request spans the version boundary.",
        (
            r"configuration_reload",
            r"hmac_keyset_reload",
            r"request_started_(?:after|before)_hmac_reload",
            r"secret_reload_does_not_log",
            r"udp_edge_credential_reload_failure",
            r"dns_target_change_is_observed_without_requiring_worker_process_restart",
        ),
        PLANNED,
        ("encore-backend", "quilkin"),
        "identified pre-reload and post-reload requests",
        "DAGGER_CONFIGURATION_RELOAD",
        "gateway configuration source",
        "configuration-source-to-gateway",
        "pre-reload request and old complete configuration version are observed",
        "application configuration-version observation proves one complete version per request",
        "new configuration version is active and control request succeeds",
        blocker="The production gateway does not expose a versioned observable hot-reload control boundary.",
    ),
    ScenarioDefinition(
        "udp_key_rotation_overlap_window",
        "Rotate the real UDP credential set and exercise the declared overlap/retirement phases.",
        (r"udp_edge_key_rotation", r"udp_edge_accepts_new_key_immediately", r"udp_edge_rejects_retired_key"),
        PLANNED,
        ("quilkin", "encore-backend"),
        "old-key, new-key, and invalid-key authenticated UDP requests",
        "DAGGER_CREDENTIAL_ROTATION",
        "gateway HMAC keyset",
        "configuration-source-to-gateway-authenticator",
        "old keyset version and authenticated control request are observed",
        "application keyset-version observation proves overlap and retirement phases",
        "new key is active, retired key is outside overlap, and control request succeeds",
        blocker="The gateway does not expose an observable versioned credential reload boundary.",
    ),
    ScenarioDefinition(
        "market_projection_out_of_order_delivery",
        "Publish identified settlement results in a declared out-of-order or stale sequence.",
        (r"out_of_order.*result", r"stale_result", r"result_arrives_before_database_replica", r"duplicate_outbox_publication", r"projection.*replica_lag"),
        IMPLEMENTED_PENDING,
        ("nsqd", "encore-backend", "postgres"),
        "versioned settlement result sequence",
        "BROKER_PUBLISH_DECLARED_RESULT_ORDER",
        "market result channel",
        "nsqd-to-market-projection",
        "durable source rows and initial projection version are observed",
        "broker and application observations record exact message IDs and delivery order",
        "all scenario-owned results reach terminal handler state and projection observation is available",
    ),
    ScenarioDefinition(
        "observability_backend_outage",
        "Make the optional observability backend unavailable during identified business work.",
        (r"(?:logging|metrics_exporter|metrics_scrape)_failure_does_not", r"observability_backpressure", r"trace_sampling_never_changes"),
        PLANNED,
        ("encore-backend", "otel-collector", "postgres"),
        "identified business request plus telemetry control event",
        "DAGGER_SCALE_OBSERVABILITY_BACKEND_TO_ZERO",
        "optional observability collector/exporter",
        "application-to-observability-backend",
        "business and telemetry control paths are healthy before outage",
        "Kubernetes zero-ready state and independent exporter probe prove outage",
        "observability backend recovers and application remains ready",
        blocker=(
            "The local Dagger deployment does not install an OpenTelemetry collector and its application "
            "configuration disables OTLP export, so a real backend outage cannot yet be established."
        ),
    ),
)


def matching_scenarios(name: str) -> list[ScenarioDefinition]:
    """Return every matching definition in canonical precedence order."""
    return [scenario for scenario in SCENARIOS if scenario.matches(name)]


def scenario_for(name: str) -> ScenarioDefinition | None:
    matches = matching_scenarios(name)
    return matches[0] if matches else None


def scenario_ids() -> set[str]:
    ids = [scenario.scenario_id for scenario in SCENARIOS]
    if len(ids) != len(set(ids)):
        raise ValueError("canonical scenario definitions contain duplicate IDs")
    return set(ids)
