apiVersion: v1
kind: Namespace
metadata:
  name: eve-trade-gateway
  labels:
    app.kubernetes.io/name: eve-trade-gateway
    app.kubernetes.io/part-of: eve-trade
    gateway.networking.k8s.io/access: public-web
    network.eve-trade.io/gateway-ingress: allowed
