apiVersion: v1
kind: ServiceAccount
metadata:
  name: public-web-istio
  namespace: eve-trade-gateway
  labels:
    app.kubernetes.io/name: public-web
    app.kubernetes.io/component: ingress-gateway
    app.kubernetes.io/part-of: eve-trade

