apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eve-trade

resources:
  - ../../base
  - postgres.yaml
  - secrets.yaml
  - local-dev-world-seed.yaml
  - quilkin.yaml
  - simulator.yaml

configMapGenerator:
  - name: local-dev-world-seed
    files:
      - local_dev_world.sql
  - name: local-runtime-database-role
    files:
      - runtime-role.sql

generatorOptions:
  disableNameSuffixHash: true

replicas:
  - name: encore-backend
    count: 1

images:
  - name: eve-trade/encore-backend
    newName: eve-trade/encore-backend
    newTag: dev
  - name: eve-trade/trade-settlement
    newName: eve-trade/trade-settlement
    newTag: dev
  - name: eve-trade/quilkin
    newName: eve-trade/quilkin
    newTag: dev
  - name: eve-trade/simulator
    newName: eve-trade/simulator
    newTag: dev

patches:
  - path: local-config-patches.yaml
