apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nsqd-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nsqd
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: encore-backend
      ports:
        - port: 4150
          protocol: TCP
