apiVersion: v1
kind: Secret
metadata:
  name: trade-settlement-database
  labels:
    app.kubernetes.io/name: trade-settlement-database
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/eve_trade
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: eve_trade
  RABBITMQ_DEFAULT_PASS: eve_trade
  RABBITMQ_DEFAULT_VHOST: /
  RABBITMQ_URL: amqp://eve_trade:eve_trade@rabbitmq:5672/
